language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: CaR+qT6DghP0bJPoRtKASNrvcccEqBAE6MyXP3U4A5bB2l2NFxiuXnG2syHYuH73h5QV7ZMBOK+9vP80lFutKlPJpIDb7osRBZ2LLMFxWejub+1G/nG6+lpKQV4x4xF/jsSws44J5ivMldHAKPZuAQ+g8k0oz82GlZI5nH4jEYpzdpVJ89r1Em9PYZjs01beMOCs1nM6LNS7N5+qi4EBNsTeze27vWLfwzpncFwk6+HxkjmLDXZzj7Zbxq4kVoBzFgU/kr8mWJJrUYvyDaiRGNKPN7okHFnHD4qfQNwKwGeCpDFw59SMCjGwTLMMe5r++YQBo/cKhboeDZOjQDkkpOWushngxwTsks0tjA9qY7goKSz7Fh8ZNVQgnR2Jce7YAd6J8FqjV414DITJhe1M9tNUlxvAMzcZk32GubJFQlAb0KuoqmcZoaErGhWuzeULevYVm67ZqVV4qKH3225AdfbCDVlEaKrcRoQThcagpIDHWyuzPEeQwdMG35Vq/7uzQ0TgXO9M3jiUC5WsgLma6L2Z+2fZEAvKEG0geLZqqQOl/s8Etj9aRXshKT90LGc5vTE6jFTTjIQxHQ41qqU6xjg3TUiAoL9dt3d9gqNS2E3UlYF12maqT2khB4OTFeX6KdvRoLcTfReHukiU2J+44faO3al3H4LrzcfG36hF17Y=
  app: my-board-game-shelf-api
  on:
    repo: derekhouck/My-Board-Game-Shelf-API
